directory: ~/Music/mpd
library: ~/Music/data/musiclibrary.db
import:
    move: yes
match:
    ignored: unmatched_tracks
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD',
                    'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.10
paths:
    default: %the{$albumartist}/$album/$track $title

plugins: convert embedart fetchart ftintitle the

convert:
    copy_album_art: yes
    dest: ~/Music/converted_by_beets

fetchart:
    sources: coverart itunes * # Prioritize itunes over others

ftintitle:
    drop: yes # Remove featured artists entirely instead of adding them to title
