directory: ~/Music/mpd
library: ~/Music/data/musiclibrary.db
asciify_paths: yes  # Avoid using unicode in filenames
import:
    move: yes
match:
    ignored: unmatched_tracks
    ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD', 'VCD',
                    'SVCD', 'UMD', 'VHS']
    strong_rec_thresh: 0.10

aunique:
    keys: albumartist album
    disambiguators: albumdisambig albumtype original_year label catalognum releasegroupdisambig
    bracket: '()'
paths:
    default: %the{$albumartist}/$album%aunique{}/$track $title

plugins: convert edit embedart fetchart ftintitle info the 

convert:
    copy_album_art: yes
    dest: ~/Music/converted_by_beets

fetchart:
    sources: coverart itunes * # Prioritize itunes over others

ftintitle:
    drop: yes # Remove featured artists entirely instead of adding them to title
